name: pokemon_yest
description: Pokemno test app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  kiwi: ^0.2.0
  kiwi_generator: ^0.4.0
  json_annotation: ^2.3.0
  http: ^0.12.0+2
  equatable: ^0.1.6
  flutter_bloc: 0.21.0
  flutter_platform_widgets: 0.20.0
  intl: ^0.16.0
  cached_network_image: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.7
  json_serializable: ^2.3.0
flutter:

  uses-material-design: true


